import supabase from "./supabase_client_v58.js";
import { requireSession, wireSignOut } from "./auth_guard_v58.js";
await requireSession("admin"); wireSignOut();
document.getElementById("btnOpenChat")?.addEventListener("click", ()=>window.ClarionChat?.open());
async function apps(){ const t=document.querySelector("#tblApplicants tbody"); if(!t) return; const { data, error }=await supabase.from("applications").select("*").order("created_at",{ascending:false}).limit(100); if(error){ t.innerHTML=`<tr><td colspan="5">${error.message}</td></tr>`; return; } t.innerHTML=""; (data||[]).forEach(a=>{ const tr=document.createElement("tr"); tr.innerHTML=`<td>${a.full_name||""}</td><td>${a.email||""}</td><td>${a.phone||""}</td><td>${a.status||"pending"}</td><td><button data-id="${a.id}" class="approve">Approve</button> <button data-id="${a.id}" class="reject">Reject</button></td>`; t.appendChild(tr); }); }
document.getElementById("tabApplicants")?.addEventListener("click", apps);
document.addEventListener("click", async e=>{ const b=e.target.closest("button.approve,button.reject"); if(!b) return; const id=b.dataset.id; const status=b.classList.contains("approve")?"approved":"rejected"; const { error }=await supabase.from("applications").update({status}).eq("id",id); if(!error){ if(status==="approved"){ const { data:app }=await supabase.from("applications").select("id,full_name,email").eq("id",id).single(); if(app) await supabase.from("profiles").upsert({ id:app.id, full_name:app.full_name, email:app.email, role:"lsp", status:"active" }); } apps(); } else alert(error.message); });
async function orders(){ const t=document.querySelector("#tblOrders tbody"); if(!t) return; const { data, error }=await supabase.from("orders").select("*").order("created_at",{ascending:false}).limit(100); if(error){ t.innerHTML=`<tr><td colspan="6">${error.message}</td></tr>`; return; } t.innerHTML=""; (data||[]).forEach(o=>{ const s=["new","confirmed","scheduled","onset","wrapped"].map(x=>`<option ${x===(o.status||"new")?"selected":""}>${x}</option>`).join(""); const tr=document.createElement("tr"); tr.innerHTML=`<td>${o.production||""}</td><td>${o.location||""}</td><td>${o.call_time||""}</td><td>${o.date?.slice?.(0,10)||""}</td><td><select data-id="${o.id}" class="st">${s}</select></td><td><button class="assign" data-id="${o.id}">Assign</button></td>`; t.appendChild(tr); }); }
document.getElementById("tabOrders")?.addEventListener("click", orders);
document.addEventListener("change", async e=>{ const el=e.target.closest("select.st"); if(!el) return; const id=el.dataset.id; await supabase.from("orders").update({ status:el.value, status_ts:new Date().toISOString() }).eq("id",id); });
async function hours(){ const t=document.querySelector("#tblHours tbody"); if(!t) return; const { data, error }=await supabase.from("hours").select("*").eq("status","submitted").order("created_at",{ascending:false}).limit(200); if(error){ t.innerHTML=`<tr><td colspan="8">${error.message}</td></tr>`; return; } t.innerHTML=""; (data||[]).forEach(h=>{ const tr=document.createElement("tr"); tr.innerHTML=`<td><input type="checkbox" class="pick" data-id="${h.id}"/></td><td>${h.lsp_name||""}</td><td>${h.production||""}</td><td>${h.location||""}</td><td>${h.start_time||""}</td><td>${h.finish_time||""}</td><td>${h.allowances||""}</td><td>${h.status||""}</td>`; t.appendChild(tr); }); }
document.getElementById("tabHours")?.addEventListener("click", hours);
document.getElementById("btnApproveHours")?.addEventListener("click", async ()=>{ const ids=[...document.querySelectorAll("#tblHours .pick:checked")].map(x=>x.dataset.id); if(!ids.length) return; const { error }=await supabase.from("hours").update({ status:"approved", approved_at:new Date().toISOString() }).in("id",ids); if(error) alert(error.message); else hours(); });
async function gps(){ const t=document.querySelector("#tblGPS tbody"); if(!t) return; const { data, error }=await supabase.from("clarion_safe").select("sender_email,lsp_name,lat,lng,timestamp,production").order("timestamp",{ascending:false}).limit(40); if(error){ t.innerHTML=`<tr><td colspan="6">${error.message}</td></tr>`; return; } t.innerHTML=""; (data||[]).forEach(g=>{ const tr=document.createElement("tr"); tr.innerHTML=`<td>${g.lsp_name||""}</td><td>${g.sender_email||""}</td><td>${g.production||""}</td><td>${g.lat?.toFixed?.(5)||""}</td><td>${g.lng?.toFixed?.(5)||""}</td><td>${new Date(g.timestamp).toLocaleString()}</td>`; t.appendChild(tr); }); }
document.getElementById("tabGPS")?.addEventListener("click", gps);
async function health(){ const t=document.querySelector("#tblHealth tbody"); if(!t) return; t.innerHTML=""; for(const n of ["profiles","applications","orders","hours","messages","clarion_safe"]){ let c="?"; try{ const { count }=await supabase.from(n).select("*",{ count:"exact", head:true }); c=count??"?"; } catch(e){ c="error"; } const tr=document.createElement("tr"); tr.innerHTML=`<td>${n}</td><td>${c}</td>`; t.appendChild(tr); } }
document.getElementById("tabHealth")?.addEventListener("click", health);
document.getElementById("tabOrders")?.click();
